#!/bin/bash

echo "🚀 LifeAID GitHub Push Script"
echo "=============================="
echo ""
echo "Your project is ready to push to GitHub!"
echo "Repository: https://github.com/Palak-Ai-2006/Life-AID.git"
echo ""
echo "📋 What's included:"
echo "✅ Complete LifeAID Emergency Response Network"
echo "✅ Healthcare signup application"
echo "✅ Responder connect platform with Gemini AI"
echo "✅ Docker deployment configuration"
echo "✅ Comprehensive documentation"
echo "✅ All source code and assets"
echo ""
echo "🔑 To push, you need a GitHub Personal Access Token:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select 'repo' permissions"
echo "4. Copy the generated token"
echo ""
echo "🚀 Then run this command:"
echo "cd /Users/khushipatel/Downloads/untitled\\ folder"
echo "git push -u origin main"
echo ""
echo "When prompted:"
echo "Username: Palak-Ai-2006"
echo "Password: [paste your token here]"
echo ""
echo "🎉 After successful push, your repository will be live at:"
echo "https://github.com/Palak-Ai-2006/Life-AID"
echo ""
echo "📱 Your application is currently running at:"
echo "Healthcare: http://localhost:3000"
echo "Responder: http://localhost:3002"
echo ""
echo "Ready to push! 🚀"
