#!/bin/bash

echo "🚀 Pushing LifeAID project to GitHub..."
echo ""
echo "Repository: https://github.com/Palak-Ai-2006/Life-AID.git"
echo ""
echo "To complete the push, you'll need to:"
echo "1. Go to https://github.com/settings/tokens"
echo "2. Generate a new Personal Access Token with 'repo' permissions"
echo "3. Copy the token"
echo ""
echo "Then run:"
echo "git push -u origin main"
echo ""
echo "When prompted:"
echo "Username: Palak-Ai-2006"
echo "Password: [paste your token here]"
echo ""
echo "Alternatively, you can push manually by running:"
echo "cd /Users/khushipatel/Downloads/untitled\\ folder"
echo "git push -u origin main"
echo ""
echo "The repository is ready with all files committed!"
